## Loading the data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
!gdown 1tWCalxQ6gGXD6sRTskh9XTjAgFH0xcNF

!gdown 1Fp6e6vf_YID8qwCNHWSbvPH5-R3HQB5N

!gdown 14q4g4K3DjIi7v8Omej9za9EmOpUeLIEH

!gdown 1TSGIJi5vcXYd398KaJpn7RXvckmttYIt

Downloading...
From: https://drive.google.com/uc?id=1tWCalxQ6gGXD6sRTskh9XTjAgFH0xcNF
To: /content/cars24_x_train.pkl
100% 1.78M/1.78M [00:00<00:00, 13.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Fp6e6vf_YID8qwCNHWSbvPH5-R3HQB5N
To: /content/cars24_X_test.pkl
100% 762k/762k [00:00<00:00, 7.80MB/s]
Downloading...
From: https://drive.google.com/uc?id=14q4g4K3DjIi7v8Omej9za9EmOpUeLIEH
To: /content/cars24_y_train.pkl
100% 112k/112k [00:00<00:00, 4.08MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TSGIJi5vcXYd398KaJpn7RXvckmttYIt
To: /content/cars24_y_test.pkl
100% 48.2k/48.2k [00:00<00:00, 59.3MB/s]

In [ ]:
X_train = pd.read_pickle('/content/cars24_x_train.pkl')
X_test = pd.read_pickle("/content/cars24_X_test.pkl")
y_train = pd.read_pickle("/content/cars24_y_train.pkl")
y_test = pd.read_pickle("/content/cars24_y_test.pkl")

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((13874, 16), (13874,), (5946, 16), (5946,))

In [ ]:
X_train

,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,0.001163,0.182500,0.118335,0.077778,0.24,0.164123,0.139801,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
1,0.005637,0.110086,0.443276,0.413027,0.20,0.805756,1.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.013007,0.136810,0.216380,0.126892,0.16,0.164123,0.348682,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.027220,0.103103,0.373667,0.091948,0.32,0.301690,0.253502,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,0.013600,0.154310,0.206754,0.134879,0.36,0.204876,0.201272,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13869,0.005111,0.164655,0.147808,0.099903,0.08,0.166142,0.217066,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
13870,0.010375,0.118966,0.177429,0.131562,0.16,0.231209,0.239112,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
13871,0.007743,0.182500,0.118335,0.077778,0.20,0.164123,0.138874,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
13872,0.014060,0.069397,0.322719,0.185185,0.36,0.301690,0.225165,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
13873,0.018271,0.147586,0.184834,0.134944,0.40,0.149901,0.106913,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()


model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_

array([-0.22864076, -0.22718566,  0.06493271,  0.04101896, -0.20803904,
        0.06292526,  0.8680704 , -0.00692582, -0.00676553,  0.00537632,
        0.13338991,  0.01451176, -0.00704768, -0.0039257 , -0.01313206,
       -0.02020274])

In [ ]:
model.intercept_

np.float64(0.11212257190753999)

In [ ]:
model.score(X_train, y_train) # R2 Score

0.9485893510587335

In [ ]:
model.score(X_test, y_test) # R2 Score

0.8019230466998655

In [ ]:
X_test.shape, y_test.shape

((5946, 16), (5946,))

In [ ]:
np.array(X_test.iloc[0,])

array([0.01827095, 0.11206897, 0.16084123, 0.        , 0.48      ,
       0.20487637, 0.30331013, 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 1.        ,
       0.        ])

In [ ]:
model.predict(np.array(X_test.iloc[0,]).reshape(1,-1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.2452726])

In [ ]:
y_test[0]

np.float64(0.050964688751365235)

In [ ]:
y_hat = model.predict(X_test)

Adj_R = 1 - ((1-model.score(X_test, y_test))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1))

In [ ]:
print("Adjusted R-squared:", Adj_R )

Adjusted R-squared: 0.8013885162136448

## Adjusted R2 score.

A higher Adjusted R-squared value indicates that the regression model explains a greater proportion of the variance in the target variable, after accounting for the number of predictors used.

## OLS - Ordinary Least Square

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

!gdown 1UpLnYA48Vy_lGUMMLG-uQE1gf_Je12Lh

Downloading...
From: https://drive.google.com/uc?id=1UpLnYA48Vy_lGUMMLG-uQE1gf_Je12Lh
To: /content/cars24-car-price-clean.csv
100% 7.10M/7.10M [00:00<00:00, 38.6MB/s]

In [ ]:
df = pd.read_csv('cars24-car-price-clean.csv')
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,-1.111046,-0.801317,1.195828,0.045745,-1.310754,-1.157780,0.801317,-0.433854,-1.125683,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
1,-0.223944,0.450030,-0.737872,-0.140402,-0.537456,-0.360203,-0.450030,-0.327501,-0.333227,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
2,-0.915058,-1.426990,0.035608,-0.582501,-0.537456,-0.404885,1.426990,-0.327501,-0.789807,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
3,-0.892365,-0.801317,-0.409143,0.329620,-0.921213,-0.693085,0.801317,-0.433854,-0.905265,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
4,-0.182683,0.137194,-0.544502,0.760085,0.042999,0.010435,-0.137194,-0.246579,-0.013096,-0.800710,-0.098382,1.014945,-0.020095,-0.056917,-0.975970,0.495818,0.444503,-0.424728

In [ ]:
y=df[['selling_price']]
X=df.drop('selling_price', axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
y_train = np.array(y_train)

In [ ]:
X_sm = sm.add_constant(X_train) # Statsmodel default is without intercept (wo), to add intercept use this code.

model_sm = sm.OLS(y_train, X_sm)

In [ ]:
model_sm

In [ ]:
results = model_sm.fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 1.588e+04
Date:                Wed, 18 Jun 2025   Prob (F-statistic):               0.00
Time:                        16:57:08   Log-Likelihood:                -7.3180
No. Observations:               15856   AIC:                             48.64
Df Residuals:                   15839   BIC:                             179.0
Df Model:                          16
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const             7.664e-05      0.002      0.040      0.968      -0.004       0.004
year                 0.0659      0.001     49.425      0.000       0.063       0.068
km_driven           -0.0160      0.002     -7.977      0.000      -0.020      -0.012
mileage             -0.0492      0.003    -14.435      0.000      -0.056      -0.043
engine               0.0307      0.005      6.378      0.000       0.021       0.040
max_power            0.0301      0.004      7.027      0.000       0.022       0.039
age                 -0.0659      0.001    -49.425      0.000      -0.068      -0.063
make                 0.0607      0.003     17.612      0.000       0.054       0.068
model                0.7919      0.005    171.030      0.000       0.783       0.801
Individual          -0.0178      0.002     -8.906      0.000      -0.022      -0.014
Trustmark Dealer    -0.0031      0.002     -1.606      0.108      -0.007       0.001
Diesel               0.0129      0.008      1.614      0.107      -0.003       0.029
Electric             0.0148      0.002      7.266      0.000       0.011       0.019
LPG                  0.0022      0.002      1.061      0.289      -0.002       0.006
Petrol              -0.0238      0.008     -2.898      0.004      -0.040      -0.008
Manual              -0.0136      0.003     -5.285      0.000      -0.019      -0.009
5                   -0.0262      0.007     -4.005      0.000      -0.039      -0.013
>5                  -0.0357      0.007     -5.168      0.000      -0.049      -0.022
==============================================================================
Omnibus:                     3788.584   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           169531.293
Skew:                           0.334   Prob(JB):                         0.00
Kurtosis:                      19.005   Cond. No.                     2.65e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.03e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
y_pred = results.predict(X_sm)

A regression model with 3 predictors has an R2 of 0.85. After adding a 4th predictor, the R2 increases to 0.86 but the adjusted R2 decreases. What can be inferred?

In [ ]:
R2 ---> Keep adding new features it will increase for every case.

Adjusted R2 score --->